### ISSUE TITLE
New script force submits form and clobbers any other javascript that may have stopped processing

### ISSUE THREAD

**Issue by oranges13** [DarkGhostHunter/Captchavel#22]
The new script fixed the issue with the Invalid Captcha Exception, but now I have noticed that it's clobbering my front-end validation because it's force submitting the form after it receives a valid captcha response.

Maybe this is a matter where I need to fire off the captcha checking manually once my validation passes, but I wanted to bring it to your attention.

I am using https://jqueryvalidation.org/ and when the form is invalid it stops the form from being submitted. Onsubmit, the recaptcha sends the request and then does the `form.submit()` anyway.

**Comment by DarkGhostHunter** [comment]
Can this be fixed with event bubbling? The idea is to make the recaptcha event listener the last to be fired. There is a [fix in stack overflow](https://stackoverflow.com/questions/47860455/how-to-ensure-an-eventlistener-is-executed-last) to ensure something executes last.

**Comment by DarkGhostHunter** [comment]
I think I figured out a patch.

I can make the script check if the submit event has been prevented. If that's the case, it won't do any logic, otherwise, it will prevent the submission until the token is received.

I think your script will prevent the submission when the data is invalid, so with the fix it won't be submitted.

Please test if it has been fixed:

    composer require darkghosthunter/captchavel:dev-master --prefer-source

**Comment by DarkGhostHunter** [comment]
I fixed it making the call sync. Basically, it will wait for the recaptcha token to resolve before submission. Since this must be done at runtime, the form may stall a while but its needed for the token check.

I could add a timer to the form. If the form token is expired, the recaptcha token would fire on submission, otherwise it would go with the unexpired token.

**Comment by oranges13** [comment]
Thanks!
